[package]
name = "web_rust"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = {version = "0.4.11", features = ["json"]}
[dependencies.rocket_auth]
version = "0.4.0"
features = ["sqlx-sqlite"]